'use client';

import { useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import jsPDF from 'jspdf';
import QRCode from 'qrcode';
import api from '@/lib/axios';
import BackButton from '@/components/BakcButton';

/* =====================
   Backend DTO Mapping
===================== */
interface StickerData {
    poId: number;
    supplierName: string;
    warehouse: string;
    receivedDate: string;
}

interface StickerDataDto {
    poId?: unknown;
    supplierName?: unknown;
    warehouse?: unknown;
    receivedDate?: unknown;
}

const toText = (value: unknown): string =>
    value === null || value === undefined ? '' : String(value);

const toNumber = (value: unknown, fallback = 0): number => {
    const n = Number(value);
    return Number.isFinite(n) ? n : fallback;
};

export default function PrintStickersPage() {
    const searchParams = useSearchParams();
    const idsParam = searchParams.get('ids');

    const [stickers, setStickers] = useState<StickerData[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    /* =====================
       Load Sticker Data
    ===================== */
    useEffect(() => {
        if (!idsParam) {
            setLoading(false);
            return;
        }

        const ids = idsParam
            .split(',')
            .map((id) => Number(id.trim()))
            .filter(Number.isFinite);

        if (!ids.length) {
            setLoading(false);
            return;
        }

        const load = async () => {
            try {
                setLoading(true);
                const res = await api.post<StickerDataDto[]>(
                    '/api/purchase-orders/stickers',
                    ids
                );

                const normalized: StickerData[] = (res.data ?? []).map(
                    (item: StickerDataDto) => ({
                        poId: toNumber(item.poId),
                        supplierName: toText(item.supplierName),
                        warehouse: toText(item.warehouse),
                        receivedDate: toText(item.receivedDate)
                    })
                );

                setStickers(normalized);
            } catch {
                setError('Failed to load sticker data');
            } finally {
                setLoading(false);
            }
        };

        load();
    }, [idsParam]);

    /* =====================
       Generate PDF
    ===================== */
    const generatePDF = async () => {
        if (!stickers.length) return;

        const pdf = new jsPDF({
            orientation: 'portrait',
            unit: 'mm',
            format: 'a6'
        });

        for (let i = 0; i < stickers.length; i++) {
            if (i > 0) pdf.addPage();
            const s = stickers[i];

            pdf.setLineWidth(0.6);
            pdf.roundedRect(4, 4, 97, 140, 4, 4);

            pdf.setFillColor(20, 20, 20);
            pdf.roundedRect(4, 4, 97, 22, 4, 4, 'F');

            pdf.setTextColor(255);
            pdf.setFont('helvetica', 'bold');
            pdf.setFontSize(15);
            pdf.text('STOCKSYNC', 10, 16);

            pdf.setFontSize(8);
            pdf.text('INVENTORY MANAGEMENT', 10, 21);
            pdf.setTextColor(0);

            pdf.setFontSize(11);
            pdf.text('GOODS RECEIVED NOTE', 10, 34);
            pdf.line(10, 36, 90, 36);

            pdf.roundedRect(8, 40, 85, 45, 3, 3);

            pdf.setFontSize(9);
            pdf.setFont('helvetica', 'bold');
            pdf.text('PO ID', 12, 48);
            pdf.text('SUPPLIER', 12, 56);
            pdf.text('WAREHOUSE', 12, 64);
            pdf.text('RECEIVED', 12, 72);

            pdf.setFont('helvetica', 'normal');
            pdf.text(toText(s.poId), 45, 48);
            pdf.text(s.supplierName, 45, 56, { maxWidth: 40 });
            pdf.text(s.warehouse, 45, 64, { maxWidth: 40 });
            pdf.text(s.receivedDate, 45, 72);

            const qr = await QRCode.toDataURL(
                JSON.stringify({ system: 'StockSync', poId: s.poId }),
                { margin: 1 }
            );

            pdf.text('VERIFICATION QR', 30, 92);
            pdf.roundedRect(25, 95, 50, 45, 3, 3);
            pdf.addImage(qr, 'PNG', 32, 100, 36, 36);

            pdf.setFontSize(7);
            pdf.text(
                'Generated by StockSync • Secure Inventory Platform',
                12,
                148
            );
        }

        pdf.save('stocksync-a6-stickers.pdf');
    };

    /* =====================
       UI States
    ===================== */
    if (loading) {
        return (
            <div className="min-h-screen flex items-center justify-center">
                Loading sticker data...
            </div>
        );
    }

    if (error) {
        return (
            <div className="min-h-screen flex items-center justify-center text-red-600">
                {error}
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-background px-6 py-8">
            {/* Top Bar */}
            <BackButton />

            <div className="max-w-6xl mx-auto mb-6">
                <button
                    onClick={generatePDF}
                    className="bg-black text-white px-6 py-3 rounded-lg font-semibold hover:bg-gray-800"
                >
                    Download Stickers (A6 PDF)
                </button>
            </div>

            {/* Sticker Preview */}
            <div className="max-w-6xl mx-auto">
                <h2 className="text-xl font-bold mb-4">
                    Sticker Preview ({stickers.length})
                </h2>

                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
                    {stickers.map((s) => (
                        <div
                            key={s.poId}
                            className="
                                rounded-xl shadow-lg p-4
                                bg-white text-black
                                dark:bg-zinc-900 dark:text-zinc-100
                                border border-zinc-200 dark:border-zinc-700
                            "
                        >
                            {/* Header */}
                            <div className="bg-black text-white rounded-lg p-3 mb-3">
                                <p className="font-bold text-sm tracking-wide">
                                    STOCKSYNC
                                </p>
                                <p className="text-xs opacity-80">
                                    INVENTORY MANAGEMENT
                                </p>
                            </div>

                            <p className="text-sm font-semibold mb-2">
                                GOODS RECEIVED NOTE
                            </p>

                            {/* Details */}
                            <div className="text-xs space-y-1">
                                <p>
                                    <span className="font-semibold">PO ID:</span>{' '}
                                    {s.poId}
                                </p>
                                <p>
                                    <span className="font-semibold">
                                        Supplier:
                                    </span>{' '}
                                    {s.supplierName}
                                </p>
                                <p>
                                    <span className="font-semibold">
                                        Warehouse:
                                    </span>{' '}
                                    {s.warehouse}
                                </p>
                                <p>
                                    <span className="font-semibold">
                                        Received:
                                    </span>{' '}
                                    {s.receivedDate}
                                </p>
                            </div>

                            {/* QR Placeholder */}
                            <div
                                className="
                                    mt-4 h-32 rounded-lg flex items-center justify-center
                                    border border-dashed
                                    border-zinc-300 dark:border-zinc-600
                                    text-zinc-500 dark:text-zinc-400
                                    text-xs
                                "
                            >
                                QR CODE
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
}
